spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rentals
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mainprojectboot@gmail.com
    password: fwtnffqxhpnqdrll
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true